#!/bin/sh

# rsync home backup
rsync -avz --ignore-errors -e ssh --delete --progress \
--exclude Downloads \
--exclude Documents/BlackmagicDesign \
--exclude GPUCache \
--exclude Music \
--exclude snap \
--exclude torrents \
--exclude Videos \
--exclude libvirt \
--exclude .linuxbrew \
--exclude .cache \
--exclude .dbus \
--exclude .mozilla \
--exclude .var \
--exclude .googleearth \
--exclude .local/share/flatpak \
/home/djwilcox macmini:rsync/ubuntu
