#!/bin/sh

# backup home to usb
rsync -aAXvz --ignore-errors --delete --progress \
--exclude Downloads \
--exclude Documents/BlackmagicDesign \
--exclude GPUCache \
--exclude Music \
--exclude roms \
--exclude snap \
--exclude torrents \
--exclude Videos \
--exclude .cache \
--exclude .dbus \
--exclude .var \
--exclude .local/share/flatpak \
/home/djwilcox /mnt/usb
