#!/bin/sh

# rsync home backup
rsync -avz --ignore-errors -e ssh --delete --progress \
--exclude Downloads \
--exclude Music \
--exclude Public \
--exclude snap \
--exclude Templates \
--exclude torrents \
--exclude .cache \
--exclude .dbus \
--exclude .var \
--exclude .local/share/flatpak \
/home/djwilcox macmini:rsync/ubuntu
