#!/bin/sh 

# remap ctrl to alt
setxkbmap -option ctrl:swap_lalt_lctl

# feh set wallpaper
feh --no-fehbg --bg-center '/home/djwilcox/Pictures/wallpaper/wallpaper.png' 

# set the cursor form xmonad
xsetroot -cursor_name left_ptr
