#!/bin/sh

# now-playing


# get the metadata from the active player
#====================================================================

metadata=$(playerctl metadata --format 'title=[{{ title }}] artist=[{{ artist }}] player=[{{ playerName }}] status=[{{ status }}] arturl=[{{ mpris:artUrl }}] position=[{{ duration(position) }}] url=[{{ xesam:url }}]')


# variables
#====================================================================

# dunst title
title=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/title/ {print $2}')

# artist
artist=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/artist/ {print $2}')

# artist fallback text
artist_fallback='Unknown'

# player name capitalized with awk
player=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/player/ {print $2}' | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')

# player status
status=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/status/ {print $2}')

# playhead position for ffmpeg thumbnail
position=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/position/ {print $2}')

# local url for ffmpeg thumbnail
url=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/url/ {print $2}' | sed 's#file://##' | tr -d '\n')


# dunst icon using mpris:artUrl
#====================================================================

# icon
icon=$(echo "${metadata}" | awk -F'[][]' -v RS=" " '/arturl/ {print $2}' | sed 's#file://##')

# fallback icon
icon_fallback='/usr/share/icons/Adwaita/48x48/legacy/face-smile.png'


# ffmpeg extract thumbnail
#====================================================================

# output file
output='/tmp/playerctl.png'

# ffmpeg function
thumbnail () {
  ffmpeg \
  -hide_banner \
  -stats -v panic \
  -ss "${position}" \
  -y \
  -i "${url}" \
  -q:v 2 -f image2 \
  -vframes 1 \
  -filter:v scale="150:-1" \
  "${output}" 2>/dev/null
}


# check url variable is not empty and run ffmpeg to create thumbnail
#====================================================================

if [ ! -z "${url}" ]; then
    thumbnail # ffmpeg thumbnail function
    icon="${output}" # set icon to ffmpeg thumbail
fi


# body - artist, player, status combined
#====================================================================

body="Artist: ${artist:=${artist_fallback}}\nPlayer: ${player}\nStatus: ${status}"


# notify-send
#====================================================================

notify-send -i "${icon:=${icon_fallback}}" "${title}" "${body}"
