#!/bin/sh

# playercrl + dunst

# get the metadata from the active player
metadata=$(playerctl metadata --format '{{ title }}#{{ artist }}#{{ playerName }}#{{ status }}#{{ mpris:artUrl }}')

# dunst title
title=$(echo "${metadata}" | cut -d '#' -f 1 --output-delimiter="\n")

# artist
artist=$(echo "${metadata}" | cut -d '#' -f 2 --output-delimiter="\n")

# artist fallback text
artist_fallback='Unknown'

# player name capitalized with awk
player=$(echo "${metadata}" | cut -d '#' -f 3 --output-delimiter="\n" | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')

# player status
status=$(echo "${metadata}" | cut -d '#' -f 4 --output-delimiter="\n")

# body - artist, player, status combined
body="Artist: ${artist:=${artist_fallback}}\nPlayer: ${player}\nStatus: ${status}"

# dunst icon using mpris:artUrl
icon=$(echo "${metadata}" | cut -d '#' -f 5 | sed 's#file://##')

# fallback icon
icon_fallback='/usr/share/icons/Adwaita/48x48/legacy/face-smile.png'

# notify-send
notify-send -i "${icon:=${icon_fallback}}" "${title}" "${body}"
