#!/bin/sh

# script usage
usage()
{
echo "\
$(basename "$0") -i url"
exit 2
}

# error messages
INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'

# if script is run arguments pass and check the options with getopts,
# else display script usage and exit
[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"

# getopts check and validate options
while getopts ':i:h' opt
do
  case ${opt} in
     i) infile="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))

# get the audio url
url=$(youtube-dl -f bestaudio -g "${infile}")

# yt function
yt () {
    if [ -z "$(mpc current)" ]; then # nothing playing
        if [ -z "$(mpc playlist)" ]; then # playlist empty
            mpc add "${url}"
            mpc play 
	else # playlist not empty so add url and play 2
           mpc add "${url}"
           mpc play 2 
	fi
    else # audio playing insert url and play next
        mpc insert "${url}" 
	mpc next
    fi
}

# run the yt function with the url
yt "${url}"
