#!/bin/sh

#===============================================================================
# ffmpeg scene detection
#===============================================================================


#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
$(basename "$0") -i infile -t 0.1 - 0.9

-i infile.(mp4|mov|mkv|m4v)
-t 0.1 - 0.9
-o output.txt"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'
NOT_MEDIA_FILE_ERR='is not a media file'


#===============================================================================
# check number of aruments passed to script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# regular expressions for the expr command
#===============================================================================

# timecode - match 000.000000
timecode='^[0-9]\{1,4\}[.]\{1\}[0-9]\{1,6\}$'


#===============================================================================
# getopts check options passed to script
#===============================================================================

while getopts ':i:t:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}";;
     t) threshold="${OPTARG}"
        expr "${threshold}" : "${timecode}" 1>/dev/null || usage;;
     h) usage;;
     o) output="${OPTARG}";;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

# get the input file name
input_nopath="${input##*/}"
input_name="${input_nopath%.*}"

# output file name
output_default="${input_name}-cutfile-$(date +"%Y-%m-%d-%H-%M-%S").txt"

# threshold default
threshold_default='0.3'


#===============================================================================
# ffprobe detection
#===============================================================================

# video duration to append to cutfile
duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${input}")

# if ffmpeg cant open the file exit
[ ! -z "${duration}" ] || usage "${input} ${NOT_MEDIA_FILE_ERR}"

# scene detection
detection=$(ffprobe -hide_banner -v panic \
-show_entries packet=pts_time \
-of default=noprint_wrappers=1:nokey=1 -f lavfi "movie=${input},select='gt(scene,"${threshold:=${threshold_default}}")'")


#===============================================================================
# create cutfile - prepend 0.0 and append duration
#===============================================================================

echo "${detection}" \
| awk 'BEGIN { printf("%f\n", '0.0') }{ printf("%s\n", $0) } END { printf("%f\n", '"${duration}"') }' \
> "${output:=${output_default}}"
