#!/bin/sh

# newsboat torrent feeds
[ -d "/etc/netns/vpn" ] \
&& doas namespace newsboat -C ~/.config/newsboat/config-torrents \
-u ~/.config/newsboat/urls-torrents -c ~/.local/share/newsboat/cache-torrents.db \
|| newsboat -C ~/.config/newsboat/config-torrents \
-u ~/.config/newsboat/urls-torrents -c ~/.local/share/newsboat/cache-torrents.db ;
