#!/bin/sh

# newsboat torrent feeds
[ -d "/etc/netns/vpn" ] \
&& namespace ~/.linuxbrew/bin/newsboat -C ~/.config/newsboat/config-torrents \
-u ~/.config/newsboat/urls-torrents -c ~/.local/share/newsboat/cache-torrents.db \
|| ~/.linuxbrew/bin/newsboat -C ~/.config/newsboat/config-torrents \
-u ~/.config/newsboat/urls-torrents -c ~/.local/share/newsboat/cache-torrents.db ;